name: Staging Deployment

on: 
  #push:
  #  branches:
  #    - master
  #pull_request:
  #  types: [closed]
  pull_request:
    types: [opened]

env:
  AZURE_WEBAPP_NAME: gumbon-test2-app  #need to check & update
  ##also need to check secrets name written below
  ## 4 secrets needed: 
  #AZURE_CREDENTIALS
  #AZURE_SUBSCRIPTION_ID
  #AZURE_PUBLISH_PROFILE   #changed on each web app, this time we only use for staging
  #GH_PAT

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      #- name: Pull request merged
      #   if: github.action == 'closed' && github.event.pull_request.merged == 'true' 
      #  run: echo merged        
      - uses: actions/checkout@v1
      - name: npm install and build webpack
        run: |
          npm install
          npm run build
          npm test
      - uses: actions/upload-artifact@master
        with:
          name: webpack artifacts
          path: public/

  Deploy-to-Azure:
    runs-on: ubuntu-latest
    needs: Build-Test
    name: Deploy app to Azure-Staging-Web app using public profile
    steps:
      - uses: Azure/webapps-deploy@v2
          with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

     
