name: Staging Deployment

on: 
  #push:
  #  branches:
  #    - master
  #pull_request:
  #  types: [closed]
  pull_request:
    types: [opened]

env:
  AZURE_WEBAPP_NAME: gumbon-test2-app  #need to check & update
  ##also need to check secrets name written below
  ## 4 secrets needed: 
  #AZURE_CREDENTIALS
  #AZURE_SUBSCRIPTION_ID
  #AZURE_PUBLISH_PROFILE   #changed on each web app, this time we only use for staging
  #GH_PAT

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        os: [ 'ubuntu-latest']
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: gumbon-test2-app
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

     
